serverFiles:
  prometheus.yml:
    rule_files:
      - /etc/prometheus/rules/*
    scrape_configs:
      - job_name: 'get_metrics'
        static_configs:
          - targets: ['ingest_data:8000']  # Update with your app's service name and port
